# Generated by Django 5.0 on 2025-09-16 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_checkoutfeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Checkout Feedback', 'verbose_name_plural': 'Checkout Feedback'},
        ),
        migrations.RemoveField(
            model_name='checkoutfeedback',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='checkoutfeedback',
            name='thoughts',
        ),
        migrations.AddField(
            model_name='checkoutfeedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checkoutfeedback',
            name='feedback_text',
            field=models.TextField(default=django.utils.timezone.now, help_text='Share your thoughts about the checkout process', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkoutfeedback',
            name='name',
            field=models.CharField(blank=True, help_text='Optional - leave blank to remain anonymous', max_length=100, null=True),
        ),
    ]
