# Generated by Django 5.0 on 2025-09-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_checkoutfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutFeedback',
        ),
    ]
